<?php

declare(strict_types=1);

namespace Qualimetrix\Analysis\Discovery;

use SplFileInfo;

/**
 * Filters out files containing `@generated` annotation.
 *
 * Reads the first 2KB of each file and checks for `@generated` as a comment annotation.
 * This prevents false positives on YACC-generated parsers, Composer autoloaders,
 * protobuf output, and other generated code.
 *
 * The pattern requires `@generated` to appear in a comment line, with at most one token
 * (e.g. a filename) between the comment marker and the annotation. This avoids matching
 * prose that merely mentions `@generated` in documentation.
 */
final class GeneratedFileFilter
{
    /**
     * Number of bytes to read from the beginning of each file.
     * 2KB is enough to cover file headers, docblocks, and annotation comments.
     */
    private const int HEADER_BYTES = 2048;

    /**
     * Pattern to detect `@generated` annotation in comment lines.
     *
     * Matches lines like:
     * - `// @generated`
     * - `// autoload.php @generated by Composer`
     *
     * - `* @generated`
     *
     * - `/* @generated * /`
     *
     * Does NOT match `@generated` embedded in prose (e.g. "files marked with `@generated`").
     */
    private const string GENERATED_PATTERN = '/^\s*(?:\/\/|\/\*+|#|\*)\s*(?:\S+\s+)?@generated\b/im';

    /**
     * Filters out generated files from a list of discovered files.
     *
     * @param list<SplFileInfo> $files
     *
     * @return list<SplFileInfo>
     */
    public function filter(array $files): array
    {
        return array_values(array_filter($files, fn(SplFileInfo $file): bool => !$this->isGenerated($file)));
    }

    /**
     * Checks if a file is marked as generated.
     *
     * Reads the first 2KB and looks for `@generated` as a comment annotation.
     */
    public function isGenerated(SplFileInfo $file): bool
    {
        $path = $file->getPathname();

        if (!is_readable($path)) {
            return false;
        }

        $handle = fopen($path, 'r');
        if ($handle === false) {
            return false;
        }

        $header = fread($handle, self::HEADER_BYTES);
        fclose($handle);

        if ($header === false || $header === '') {
            return false;
        }

        return preg_match(self::GENERATED_PATTERN, $header) === 1;
    }
}
