<?php

declare(strict_types=1);

namespace Qualimetrix\Tests\Unit\Analysis\Discovery;

use FilesystemIterator;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Qualimetrix\Analysis\Discovery\GeneratedFileFilter;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;

#[CoversClass(GeneratedFileFilter::class)]
final class GeneratedFileFilterTest extends TestCase
{
    private string $tempDir;

    protected function setUp(): void
    {
        $this->tempDir = sys_get_temp_dir() . '/qmx-generated-test-' . uniqid();
        mkdir($this->tempDir, 0755, true);
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->tempDir);
    }

    #[Test]
    public function itFiltersOutGeneratedFiles(): void
    {
        $generated = $this->createFile('Generated.php', "<?php\n/** @generated */\nclass Generated {}");
        $normal = $this->createFile('Normal.php', "<?php\nclass Normal {}");

        $filter = new GeneratedFileFilter();
        $result = $filter->filter([
            new SplFileInfo($generated),
            new SplFileInfo($normal),
        ]);

        self::assertCount(1, $result);
        self::assertSame('Normal.php', $result[0]->getFilename());
    }

    #[Test]
    public function itKeepsAllFilesWhenNoneAreGenerated(): void
    {
        $file1 = $this->createFile('A.php', "<?php\nclass A {}");
        $file2 = $this->createFile('B.php', "<?php\nclass B {}");

        $filter = new GeneratedFileFilter();
        $result = $filter->filter([
            new SplFileInfo($file1),
            new SplFileInfo($file2),
        ]);

        self::assertCount(2, $result);
    }

    #[Test]
    public function itDetectsGeneratedCaseInsensitively(): void
    {
        $file1 = $this->createFile('Upper.php', "<?php\n/** @GENERATED */\nclass Upper {}");
        $file2 = $this->createFile('Mixed.php', "<?php\n/** @Generated */\nclass Mixed {}");
        $file3 = $this->createFile('Lower.php', "<?php\n/** @generated */\nclass Lower {}");

        $filter = new GeneratedFileFilter();
        $result = $filter->filter([
            new SplFileInfo($file1),
            new SplFileInfo($file2),
            new SplFileInfo($file3),
        ]);

        self::assertCount(0, $result);
    }

    #[Test]
    public function itOnlyChecksFirst2KbOfFile(): void
    {
        // @generated after 2KB should NOT be detected
        $content = "<?php\n" . str_repeat("// padding line\n", 200) . "/** @generated */\nclass Late {}";
        self::assertGreaterThan(2048, \strlen($content), 'Test content must exceed 2KB');

        $file = $this->createFile('Late.php', $content);

        $filter = new GeneratedFileFilter();
        $result = $filter->filter([new SplFileInfo($file)]);

        self::assertCount(1, $result, 'File with @generated after 2KB should not be filtered');
    }

    #[Test]
    public function itDetectsGeneratedWithinFirst2Kb(): void
    {
        // @generated within 2KB should be detected
        $content = "<?php\n/** @generated */\n" . str_repeat("// padding line\n", 200);

        $file = $this->createFile('Early.php', $content);

        $filter = new GeneratedFileFilter();
        $result = $filter->filter([new SplFileInfo($file)]);

        self::assertCount(0, $result, 'File with @generated within 2KB should be filtered');
    }

    #[Test]
    #[DataProvider('generatedAnnotationVariantsProvider')]
    public function itDetectsVariousAnnotationFormats(string $content, bool $shouldBeFiltered): void
    {
        $file = $this->createFile('Test.php', $content);

        $filter = new GeneratedFileFilter();
        $result = $filter->filter([new SplFileInfo($file)]);

        if ($shouldBeFiltered) {
            self::assertCount(0, $result, 'File should be filtered as generated');
        } else {
            self::assertCount(1, $result, 'File should NOT be filtered');
        }
    }

    /**
     * @return iterable<string, array{string, bool}>
     */
    public static function generatedAnnotationVariantsProvider(): iterable
    {
        yield 'docblock @generated' => [
            "<?php\n/**\n * @generated\n */\nclass Foo {}",
            true,
        ];

        yield 'inline comment @generated' => [
            "<?php\n// @generated\nclass Foo {}",
            true,
        ];

        yield 'block comment @generated' => [
            "<?php\n/* @generated */\nclass Foo {}",
            true,
        ];

        yield '@generated with text after' => [
            "<?php\n/** @generated by protoc */\nclass Foo {}",
            true,
        ];

        yield 'no @generated' => [
            "<?php\nclass Foo {}",
            false,
        ];

        yield '@generated in string literal' => [
            "<?php\n\$x = '@generated';\nclass Foo {}",
            false, // String literals are not comment annotations
        ];

        yield 'Composer autoloader format' => [
            "<?php\n\n// autoload_psr4.php @generated by Composer\n\nreturn [];",
            true,
        ];

        yield 'Composer scoper format' => [
            "<?php\n\n// scoper-autoload.php @generated by PhpScoper\n\nreturn [];",
            true,
        ];

        yield '@generated in docblock param description' => [
            "<?php\n/**\n * @param bool \$includeGenerated Whether to include files marked with @generated annotation\n */\nclass Foo {}",
            false, // Prose mentioning @generated is not a generated file
        ];

        yield '@generated in prose documentation' => [
            "<?php\n/**\n * Filters out files containing @generated annotation.\n */\nclass Foo {}",
            false,
        ];

        yield 'hash comment @generated' => [
            "<?php\n# @generated\nclass Foo {}",
            true,
        ];

        yield '@generated on same line as php open tag' => [
            "<?php /* @generated by some-tool */\nclass Foo {}",
            false, // No known generator uses this format; all put @generated on a separate comment line
        ];
    }

    #[Test]
    public function itHandlesEmptyFileList(): void
    {
        $filter = new GeneratedFileFilter();
        $result = $filter->filter([]);

        self::assertSame([], $result);
    }

    #[Test]
    public function itReturnsReindexedArray(): void
    {
        $generated = $this->createFile('Generated.php', "<?php\n/** @generated */\nclass G {}");
        $normal = $this->createFile('Normal.php', "<?php\nclass N {}");

        $filter = new GeneratedFileFilter();
        $result = $filter->filter([
            new SplFileInfo($generated),
            new SplFileInfo($normal),
        ]);

        self::assertSame([0], array_keys($result), 'Result array should be re-indexed');
    }

    #[Test]
    public function isGeneratedReturnsTrueForGeneratedFile(): void
    {
        $file = $this->createFile('Gen.php', "<?php\n/** @generated */\nclass Gen {}");

        $filter = new GeneratedFileFilter();
        self::assertTrue($filter->isGenerated(new SplFileInfo($file)));
    }

    #[Test]
    public function isGeneratedReturnsFalseForNormalFile(): void
    {
        $file = $this->createFile('Normal.php', "<?php\nclass Normal {}");

        $filter = new GeneratedFileFilter();
        self::assertFalse($filter->isGenerated(new SplFileInfo($file)));
    }

    private function createFile(string $name, string $content): string
    {
        $path = $this->tempDir . '/' . $name;
        file_put_contents($path, $content);

        return $path;
    }

    private function removeDirectory(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        $items = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
            RecursiveIteratorIterator::CHILD_FIRST,
        );

        foreach ($items as $item) {
            if ($item->isDir()) {
                rmdir($item->getPathname());
            } else {
                unlink($item->getPathname());
            }
        }

        rmdir($dir);
    }
}
