<?php

declare(strict_types=1);

namespace QmxDirectiveAudit;

use QmxFindingGate\Process;
use RuntimeException;

/**
 * `composer check:self`'s own wrapper around `bin/qmx directives src/`.
 *
 * `DirectivesCommand::exitCodeFor()` returns 0 on an empty or all-`Unmeasured`
 * verdict list — correctly, for the user-facing command: a tree with no
 * directives is not an error. But that same leniency means this CI step would
 * stay green through a regression in directive extraction, a widened
 * addressability refusal, or an `exclude_paths`/`exclude_namespaces` entry that
 * eats the analysed file set: every one of those shrinks or empties what the
 * audit judges without the audit's own exit code ever noticing.
 *
 * The fix is not to change the command — the empty-tree answer is correct — but
 * two checks of its own, run in this order:
 *
 * 1. **Population**, by multiset: the audit's `@qmx-threshold` sites
 *    (`file:line:target`, one count per occurrence) must match, occurrence for
 *    occurrence, the population
 *    `docs/internal/plans/rule-vocabulary/enumeration-threshold-directives.tsv`
 *    records — generated by {@see ../enumerate-inline-directives.php}
 *    through a tokenizer scan of `src/` that consults no configuration and so
 *    cannot be narrowed by one. A plain set diff would collapse two authored
 *    directives on the same site into one and never notice one of them going
 *    missing; {@see Population::diff()} does not.
 *
 *    **The two measures are written differently on purpose.** The enumeration
 *    used to hold a hand-copied duplicate of
 *    {@see \Qualimetrix\Analysis\Policy\Inline\Contract\ThresholdOverrideExtractor}'s
 *    private extraction pattern, kept byte-identical to it by a test — so a
 *    regression inside the pattern (a character class narrowed, an anchor
 *    loosened) was authored once and landed in both measurements, and this
 *    check could not see the one class of defect the pair exists for.
 *    {@see ThresholdDirectiveScan} shares no expression with the product: it
 *    reads a docblock line word by word and cuts the target with a character
 *    list of its own. Nothing forces those two spellings together, so
 *    `ThresholdPopulationAgreementTest` asserts what actually matters — that
 *    they answer alike on a fixture of authored forms, including the six
 *    character classes `src/` happens never to use. On top of that this check
 *    still catches every disagreement that is not pattern-level: the audit and
 *    the enumerator reach their answer through unrelated pipelines — file
 *    discovery, `exclude_paths`/`exclude_namespaces`, addressability refusal,
 *    rule selection — and none of that machinery is shared.
 *
 * 2. **Non-emptiness of what was actually measured**: population matching is
 *    silent when every `@qmx-threshold` site becomes
 *    `DirectiveEffect::Unmeasured` — a widened addressability refusal or a
 *    disabled producer removes nothing from the population the multiset diff
 *    sees, it just stops any of those sites from being judged. So once the
 *    populations agree and are non-empty, this gate also demands at least one
 *    verdict {@see MeasuredEffects} calls a measurement — the same floor
 *    {@see ../directive-narrow-control.php} enforces on each half of its own
 *    comparison, and now the same code rather than the same sentence twice.
 *
 * What counts as a measurement is a frozen table, not "anything not named
 * unmeasured": that phrasing made every verdict value the vocabulary might grow
 * count as one, silently and on the lenient side.
 */
final class Gate
{
    private const string ROOT = __DIR__ . '/../..';

    private const string TARGET = 'src/';

    /** Distinct from the audit's own exit codes (0-4): a population mismatch is this gate's own finding. */
    private const int EXIT_POPULATION_MISMATCH = 5;

    /** All `@qmx-threshold` sites matched the enumeration, but not one produced a measured verdict. */
    private const int EXIT_NO_MEASURED_VERDICTS = 6;

    /** The report or the enumeration is not of a shape this gate knows how to read. */
    private const int EXIT_UNREADABLE = 7;

    private const int FAILURE = 1;

    public static function main(): int
    {
        $audit = self::runAudit();

        fwrite(\STDERR, $audit['stderr']);

        return self::judge(
            $audit['stdout'],
            $audit['exit'],
            static fn(): string => self::runEnumeration(),
            static function (string $payload): void {
                fwrite(\STDOUT, $payload);
            },
            static function (string $diagnostic): void {
                fwrite(\STDERR, $diagnostic);
            },
        );
    }

    /**
     * The judgement, over captured output rather than over two processes.
     *
     * Separated from {@see main()} so it can be exercised on a synthetic report:
     * a floor whose only evidence is a green run over the live tree is a floor
     * nobody has seen refuse anything.
     *
     * The report is the payload and everything this gate says about it is a
     * diagnostic, on two sinks rather than one: a caller piping the JSON
     * report into another tool must not receive this gate's sentences in the
     * same stream, and a reader looking for the refusal must not have to find
     * it inside a report.
     *
     * @param callable(): string $enumeration the authored population, as TSV, fetched only if it is needed
     * @param callable(string): void $write the report, as the command produced it
     * @param callable(string): void $note this gate's own diagnostics
     */
    public static function judge(
        string $auditStdout,
        int $auditExit,
        callable $enumeration,
        callable $write,
        callable $note,
    ): int {
        try {
            return self::decide($auditStdout, $auditExit, $enumeration, $write, $note);
        } catch (AuditReportError $error) {
            $note('UNREADABLE: ' . $error->getMessage() . "\n");

            return self::EXIT_UNREADABLE;
        }
    }

    /**
     * @param callable(): string $enumeration
     * @param callable(string): void $write
     * @param callable(string): void $note
     *
     * @throws AuditReportError
     */
    private static function decide(
        string $auditStdout,
        int $auditExit,
        callable $enumeration,
        callable $write,
        callable $note,
    ): int {
        // Whether the command emitted a report at all is a question about the
        // command, not about the report, and its answer is the command's own
        // exit code. Asking it before reading is what keeps a run that died
        // before writing anything from being reported as a malformed report.
        if (!\is_array(json_decode($auditStdout, true))) {
            $note(\sprintf(
                "directives:audit produced no parseable JSON (exit %d).\nstdout: %s\n",
                $auditExit,
                $auditStdout,
            ));

            return $auditExit !== 0 ? $auditExit : self::FAILURE;
        }

        $write($auditStdout);

        // 3 (config error) and 4 (incomplete run) already disqualify the report
        // from judging anything; nothing this gate adds changes that verdict,
        // and refusing such a run over the shape of a report nobody is going to
        // read would replace the command's own answer with this gate's.
        if ($auditExit !== 0 && $auditExit !== 2) {
            return $auditExit;
        }

        $report = VerdictReport::fromJson($auditStdout);

        if ($report->isErrorEnvelope()) {
            // The command already chose an exit code for this; ours is only to
            // propagate it, not to reinterpret it.
            return $auditExit;
        }

        $auditedSites = self::sitesOf($report->thresholdVerdicts());
        $enumeratedSites = self::enumeratedSitesOf($enumeration());

        [$onlyAudited, $onlyEnumerated] = Population::diff($auditedSites, $enumeratedSites);

        if ($onlyAudited !== [] || $onlyEnumerated !== []) {
            $note(\sprintf(
                "POPULATION MISMATCH: audit judged %d @qmx-threshold site(s), enumeration found %d.\n",
                \count($auditedSites),
                \count($enumeratedSites),
            ));
            foreach ($onlyEnumerated as $site => $missing) {
                $note(\sprintf("  enumerated but not judged: %s (x%d)\n", $site, $missing));
            }
            foreach ($onlyAudited as $site => $surplus) {
                $note(\sprintf("  judged but not enumerated: %s (x%d)\n", $site, $surplus));
            }

            return self::EXIT_POPULATION_MISMATCH;
        }

        if ($auditedSites === []) {
            $note("population check: no @qmx-threshold sites in scope; nothing to floor-check.\n");

            return $auditExit;
        }

        $measured = $report->measuredThresholdCount();

        if ($measured === 0) {
            $note(\sprintf(
                "ALL @qmx-THRESHOLD VERDICTS UNMEASURED: %d site(s) match the enumeration exactly, but not one" .
                    " produced a measured verdict — every one is `effect === \"unmeasured\"`. Population agreement" .
                    " alone does not prove the audit judged anything.\n",
                \count($auditedSites),
            ));

            return self::EXIT_NO_MEASURED_VERDICTS;
        }

        $note(\sprintf(
            "population check: %d @qmx-threshold site(s) in the audit match the enumeration exactly, %d measured.\n",
            \count($auditedSites),
            $measured,
        ));

        return $auditExit;
    }

    /**
     * @param list<AuditedVerdict> $verdicts
     *
     * @return list<string>
     */
    private static function sitesOf(array $verdicts): array
    {
        $sites = array_map(static fn(AuditedVerdict $verdict): string => $verdict->site(), $verdicts);
        sort($sites);

        return $sites;
    }

    /**
     * @throws AuditReportError
     *
     * @return list<string>
     */
    private static function enumeratedSitesOf(string $tsv): array
    {
        $sites = array_map(
            static fn(EnumeratedSite $site): string => $site->site(),
            SiteEnumeration::fromTsv($tsv),
        );
        sort($sites);

        return $sites;
    }

    /** @return array{stdout: string, stderr: string, exit: int} */
    private static function runAudit(): array
    {
        return Process::run(
            ['php', 'bin/qmx', 'directives', self::TARGET, '--format=json'],
            self::rootPath(),
        );
    }

    /** One authored `@qmx-threshold` site per line, as `file\tline\tchannel\tvalues`. */
    private static function runEnumeration(): string
    {
        $result = Process::run(['php', 'scripts/enumerate-inline-directives.php', 'src'], self::rootPath());

        if ($result['exit'] !== 0) {
            throw new RuntimeException(\sprintf(
                "enumerate-inline-directives.php failed (exit %d):\n%s",
                $result['exit'],
                $result['stderr'],
            ));
        }

        return $result['stdout'];
    }

    private static function rootPath(): string
    {
        $resolved = realpath(self::ROOT);

        if ($resolved === false) {
            throw new RuntimeException('Cannot resolve the repository root.');
        }

        return $resolved;
    }
}
