<?php

declare(strict_types=1);

namespace Qualimetrix\Analysis\Run\Discovery;

use Qualimetrix\Analysis\Run\Contract\Discovery\GeneratedFileFilterInterface;

use SplFileInfo;

/**
 * Filters out files containing `@generated` annotation.
 *
 * Reads the first 2KB of each file and checks for `@generated` as a comment annotation.
 * This prevents false positives on YACC-generated parsers, Composer autoloaders,
 * protobuf output, and other generated code.
 *
 * The pattern requires `@generated` to appear in a comment line, with at most one token
 * (e.g. a filename) between the comment marker and the annotation. This avoids matching
 * prose that merely mentions `@generated` in documentation.
 */
final class GeneratedFileFilter implements GeneratedFileFilterInterface
{
    /**
     * Number of bytes to read from the beginning of each file.
     * 2KB is enough to cover file headers, docblocks, and annotation comments.
     */
    private const int HEADER_BYTES = 2048;

    /**
     * Pattern to detect `@generated` annotation in comment lines.
     *
     * Matches lines like:
     * - `// @generated`
     * - `// autoload.php @generated by Composer`
     *
     * - `* @generated`
     *
     * - `/* @generated * /`
     *
     * Does NOT match `@generated` embedded in prose (e.g. "files marked with `@generated`").
     */
    private const string GENERATED_PATTERN = '/^\s*(?:\/\/|\/\*+|#|\*)\s*(?:\S+\s+)?@generated\b/im';

    /**
     * Checks if a file is marked as generated.
     *
     * Reads the first 2KB and looks for `@generated` as a comment annotation.
     *
     * Readability is not enough to justify reading. `fopen()` succeeds on a
     * directory and `fread()` then raises a PHP notice, which the CLI writes to
     * **stdout** — in front of the JSON, SARIF or Checkstyle document the
     * caller is parsing. This is the only place a file's bytes are read before
     * the parser sees it, so the regular-file question is asked here too and
     * not left to whoever hands the list over.
     */
    public function isGenerated(SplFileInfo $file): ?bool
    {
        $path = $file->getPathname();

        if (!is_file($path) || !is_readable($path)) {
            return null;
        }

        $handle = @fopen($path, 'rb');
        if ($handle === false) {
            return null;
        }

        // @qmx-ignore-next-line code-smell.error-suppression -- A failed header read remains null and becomes UnreadableFile; interpreter notices must not precede the report document.
        $header = @fread($handle, self::HEADER_BYTES);
        fclose($handle);

        if ($header === false) {
            return null;
        }

        return preg_match(self::GENERATED_PATTERN, $header) === 1;
    }
}
