<?php

declare(strict_types=1);

namespace Qualimetrix\Infrastructure\Console\Hook;

/**
 * The pre-commit hook this CLI installs: its text, its marker, and what counts
 * as ours.
 *
 * The text is generated rather than shipped. `/scripts/` is `export-ignore`d,
 * so a hook script living there reaches no consumer: `hook:install` from an
 * installed package answered `Hook script not found` and exited 1 — measured,
 * not inferred. Shipping the file instead would keep a delivery step between
 * the command and the one input it actually needs, the path of the binary
 * doing the installing, which the command already holds.
 *
 * The marker lives here because it is the same string for the command that
 * writes the hook and the two that recognise it. It used to be a private
 * constant in each of those two, so the copies could drift apart and nothing
 * would notice.
 */
final class PreCommitHook
{
    /**
     * The line that makes a hook file ours.
     *
     * It is a comment inside {@see TEMPLATE}; moving or rewording it there
     * orphans every hook already installed, which then reads as third-party.
     */
    public const string MARKER = 'Qualimetrix pre-commit hook';

    /**
     * Where {@see script()} substitutes the binary path.
     *
     * A placeholder rather than a format specifier: the template is shell and
     * carries `%` of its own, which `sprintf` would consume.
     */
    private const string BINARY_PLACEHOLDER = '@QMX_BINARY@';

    /**
     * Nowdoc, deliberately: the template is full of shell variables, and a
     * heredoc would interpolate `$QMX_BIN` and `$STAGED_FILES` away at PHP
     * level before git ever saw them.
     */
    private const string TEMPLATE = <<<'SH'
        #!/bin/bash
        # ============================================================================
        # Qualimetrix pre-commit hook
        # ============================================================================
        # Generated by `qmx hook:install`. Analyzes staged PHP files before commit and
        # blocks the commit when violations are found.
        #
        # Reinstall after moving the binary: qmx hook:install --force
        # ============================================================================

        set -e

        # The binary that installed this hook. The fallbacks below cover it moving
        # afterwards, which `composer update` does to vendor/ routinely.
        QMX_BIN="@QMX_BINARY@"

        if [ ! -f "$QMX_BIN" ]; then
            if [ -f "vendor/bin/qmx" ]; then
                QMX_BIN="vendor/bin/qmx"
            elif [ -f "bin/qmx" ]; then
                QMX_BIN="bin/qmx"
            else
                echo "❌ Error: qmx binary not found."
                echo "Reinstall the hook: qmx hook:install --force"
                exit 1
            fi
        fi

        # Staged PHP files, deletions excluded
        STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

        if [ -z "$STAGED_FILES" ]; then
            exit 0
        fi

        echo "🔍 Running Qualimetrix on staged files..."
        echo ""

        FILES_ARGS=$(echo "$STAGED_FILES" | tr '\n' ' ')

        BASELINE_ARG=""
        if [ -f "baseline.json" ]; then
            BASELINE_ARG="--baseline=baseline.json"
            BASELINE_ADVICE="Replace accepted levels intentionally: $QMX_BIN baseline:generate baseline.json src/ --force"
        else
            BASELINE_ADVICE="Create a baseline: $QMX_BIN baseline:generate baseline.json src/"
        fi

        if "$QMX_BIN" check $FILES_ARGS $BASELINE_ARG; then
            echo ""
            echo "✅ Qualimetrix passed."
            exit 0
        else
            EXIT_CODE=$?
            echo ""
            echo "❌ Qualimetrix found issues."
            echo ""
            echo "Options:"
            echo "  - Fix the issues and try again"
            echo "  - $BASELINE_ADVICE"
            echo "  - Skip this check: git commit --no-verify"
            exit $EXIT_CODE
        fi

        SH;

    /**
     * The hook file's contents, bound to the binary that is installing it.
     *
     * @param string $qmxBinary absolute path to the running qmx binary
     */
    public static function script(string $qmxBinary): string
    {
        return str_replace(self::BINARY_PLACEHOLDER, $qmxBinary, self::TEMPLATE);
    }

    /**
     * Whether a hook file's contents are one of ours.
     */
    public static function isOurs(string $contents): bool
    {
        return str_contains($contents, self::MARKER);
    }
}
