<?php

declare(strict_types=1);

namespace Qualimetrix\Infrastructure\Console\Hook;

/**
 * The pre-commit hook this CLI installs: its text, its marker, and what counts
 * as ours.
 *
 * The text is generated rather than shipped. `/scripts/` is `export-ignore`d,
 * so a hook script living there reaches no consumer: `hook:install` from an
 * installed package answered `Hook script not found` and exited 1 — measured,
 * not inferred. Shipping the file instead would keep a delivery step between
 * the command and the one input it actually needs, the path of the binary
 * doing the installing, which the command already holds.
 *
 * The marker lives here because it is the same string for the command that
 * writes the hook and the two that recognise it. It used to be a private
 * constant in each of those two, so the copies could drift apart and nothing
 * would notice.
 */
final class PreCommitHook
{
    /**
     * The line that makes a hook file ours.
     *
     * It is a comment inside {@see TEMPLATE}; moving or rewording it there
     * orphans every hook already installed, which then reads as third-party.
     */
    public const string MARKER = 'Qualimetrix pre-commit hook';

    /**
     * Where {@see script()} substitutes the binary path.
     *
     * A placeholder rather than a format specifier: the template is shell and
     * carries `%` of its own, which `sprintf` would consume.
     */
    private const string BINARY_PLACEHOLDER = '@QMX_BINARY@';

    /**
     * Nowdoc, deliberately: the template is full of shell variables, and a
     * heredoc would interpolate `$QMX_BIN` and `$STAGED_FILES` away at PHP
     * level before git ever saw them.
     */
    private const string TEMPLATE = <<<'SH'
        #!/bin/bash
        # ============================================================================
        # Qualimetrix pre-commit hook
        # ============================================================================
        # Generated by `qmx hook:install`. Analyzes staged PHP files before commit and
        # blocks the commit when violations are found.
        #
        # Reinstall after moving the binary: qmx hook:install --force
        # ============================================================================

        set -e
        set -o pipefail

        # The binary that installed this hook. The fallbacks below cover it moving
        # afterwards, which `composer update` does to vendor/ routinely.
        QMX_BIN=@QMX_BINARY@

        # -x, not -f: a file that cannot be executed cannot run the analysis, and
        # treating it as present would report its failure as a finding.
        if [ ! -x "$QMX_BIN" ]; then
            if [ -x "vendor/bin/qmx" ]; then
                QMX_BIN="vendor/bin/qmx"
            elif [ -x "bin/qmx" ]; then
                QMX_BIN="bin/qmx"
            else
                echo "❌ Error: qmx binary not found or not executable."
                echo "Reinstall the hook: qmx hook:install --force"
                exit 1
            fi
        fi

        # NUL-delimited, because a path may contain a space and splitting on one
        # would hand the analyser two paths that do not exist. Do not use process
        # substitution here: it hides git's status, so a failed enumeration could
        # otherwise look like an empty staged-file set.
        if STAGED_FILE_LIST=$(mktemp "${TMPDIR:-/tmp}/qmx-pre-commit.XXXXXX"); then
            :
        else
            EXIT_CODE=$?
            echo "❌ Could not create a temporary staged-file list (exit $EXIT_CODE). Nothing was analysed."
            exit $EXIT_CODE
        fi

        if [ -z "$STAGED_FILE_LIST" ]; then
            echo "❌ Could not create a temporary staged-file list. Nothing was analysed."
            exit 1
        fi

        cleanup_staged_file_list() {
            EXIT_CODE=$?
            rm -f -- "$STAGED_FILE_LIST" || :
            trap - EXIT
            exit $EXIT_CODE
        }
        trap cleanup_staged_file_list EXIT

        if git diff --cached --name-only -z --diff-filter=ACM -- '*.php' > "$STAGED_FILE_LIST"; then
            :
        else
            EXIT_CODE=$?
            echo "❌ Could not enumerate staged PHP files (exit $EXIT_CODE). Nothing was analysed."
            exit $EXIT_CODE
        fi

        if [ ! -f "$STAGED_FILE_LIST" ] || [ ! -r "$STAGED_FILE_LIST" ]; then
            echo "❌ Could not read the staged-file list. Nothing was analysed."
            exit 1
        fi

        if STAGED_FILE_COUNT=$(LC_ALL=C tr -cd '\000' < "$STAGED_FILE_LIST" | wc -c | tr -d '[:space:]'); then
            :
        else
            EXIT_CODE=$?
            echo "❌ Could not read the staged-file list (exit $EXIT_CODE). Nothing was analysed."
            exit $EXIT_CODE
        fi

        if [ -s "$STAGED_FILE_LIST" ]; then
            if LAST_STAGED_FILE_BYTE=$(LC_ALL=C tail -c 1 "$STAGED_FILE_LIST" | od -An -t u1 | tr -d '[:space:]'); then
                :
            else
                EXIT_CODE=$?
                echo "❌ Could not read the staged-file list (exit $EXIT_CODE). Nothing was analysed."
                exit $EXIT_CODE
            fi

            if [ "$LAST_STAGED_FILE_BYTE" != "0" ]; then
                echo "❌ The staged-file list is incomplete. Nothing was analysed."
                exit 1
            fi
        fi

        if exec 3< "$STAGED_FILE_LIST"; then
            :
        else
            EXIT_CODE=$?
            echo "❌ Could not read the staged-file list (exit $EXIT_CODE). Nothing was analysed."
            exit $EXIT_CODE
        fi

        STAGED_FILES=()
        STAGED_FILES_READ=0
        while IFS= read -r -d '' staged_file; do
            STAGED_FILES+=("$staged_file")
            STAGED_FILES_READ=$((STAGED_FILES_READ + 1))
        done <&3
        exec 3<&-

        if [ "$STAGED_FILES_READ" -ne "$STAGED_FILE_COUNT" ]; then
            echo "❌ Could not read the complete staged-file list. Nothing was analysed."
            exit 1
        fi

        if [ ${#STAGED_FILES[@]} -eq 0 ]; then
            exit 0
        fi

        echo "🔍 Running Qualimetrix on staged files..."
        echo ""

        BASELINE_ARGS=()
        if [ -f "baseline.json" ]; then
            BASELINE_ARGS=(--baseline=baseline.json)
            BASELINE_ADVICE="Replace accepted levels intentionally: $QMX_BIN baseline:generate baseline.json src/ --force"
        else
            BASELINE_ADVICE="Create a baseline: $QMX_BIN baseline:generate baseline.json src/"
        fi

        if "$QMX_BIN" check "${STAGED_FILES[@]}" ${BASELINE_ARGS[@]+"${BASELINE_ARGS[@]}"}; then
            echo ""
            echo "✅ Qualimetrix passed."
            exit 0
        else
            EXIT_CODE=$?
        fi

        # 126 and 127 come from the shell, not from the analysis: the binary could
        # not be executed or was not found at all. Reporting them as findings would
        # send the reader off to write a baseline for violations nobody measured.
        if [ $EXIT_CODE -eq 126 ] || [ $EXIT_CODE -eq 127 ]; then
            echo ""
            echo "❌ Could not run $QMX_BIN (exit $EXIT_CODE). Nothing was analysed."
            echo "Reinstall the hook: qmx hook:install --force"
            exit $EXIT_CODE
        fi

        echo ""
        echo "❌ Qualimetrix found issues."
        echo ""
        echo "Options:"
        echo "  - Fix the issues and try again"
        echo "  - $BASELINE_ADVICE"
        echo "  - Skip this check: git commit --no-verify"
        exit $EXIT_CODE

        SH;

    /**
     * The hook file's contents, bound to the binary that is installing it.
     *
     * @param string $qmxBinary absolute path to the running qmx binary
     */
    public static function script(string $qmxBinary): string
    {
        return str_replace(self::BINARY_PLACEHOLDER, self::quoted($qmxBinary), self::TEMPLATE);
    }

    /**
     * Whether a hook file's contents are one of ours.
     */
    public static function isOurs(string $contents): bool
    {
        return str_contains($contents, self::MARKER);
    }

    /**
     * One shell word, whatever the path contains.
     *
     * Double quotes were not enough and the difference is not theoretical: a
     * path carrying `"` ended the string early and the whole file stopped
     * being valid shell, while `$HOME` or `$(id -u)` in a directory name was
     * expanded — the second one executing on every commit. Single quotes
     * suspend all of that, and the only character they cannot carry is `'`,
     * which is closed, escaped and reopened.
     */
    private static function quoted(string $value): string
    {
        return "'" . str_replace("'", "'\\''", $value) . "'";
    }
}
