<?php

declare(strict_types=1);

namespace QmxDirectiveAuditGate;

use QmxFindingGate\Process;
use RuntimeException;

/**
 * `composer check:self`'s own wrapper around `bin/qmx directives src/`.
 *
 * `DirectivesCommand::exitCodeFor()` returns 0 on an empty or all-`Unmeasured`
 * verdict list — correctly, for the user-facing command: a tree with no
 * directives is not an error. But that same leniency means this CI step would
 * stay green through a regression in directive extraction, a widened
 * addressability refusal, or an `exclude_paths`/`exclude_namespaces` entry that
 * eats the analysed file set: every one of those shrinks or empties what the
 * audit judges without the audit's own exit code ever noticing.
 *
 * The fix is not to change the command — the empty-tree answer is correct — but
 * to hold its `@qmx-threshold` population against the one other measurement of
 * the same population this repository already keeps:
 * `docs/internal/plans/rule-vocabulary/enumeration-threshold-directives.tsv`,
 * generated by {@see ../scripts/enumerate-inline-directives.php} through a
 * tokenizer scan of `src/` that consults no configuration and so cannot be
 * narrowed by one. Two measurements of one set, taken by unrelated code paths,
 * that must reach the same answer — a disagreement between them is cheaper to
 * trust than either alone.
 */

require __DIR__ . '/finding-gate/GateError.php';
require __DIR__ . '/finding-gate/Process.php';

final class Gate
{
    private const string ROOT = __DIR__ . '/..';

    private const string TARGET = 'src/';

    /** Distinct from the audit's own exit codes (0-4): a population mismatch is this gate's own finding. */
    private const int EXIT_POPULATION_MISMATCH = 5;

    private const int FAILURE = 1;

    public static function main(): int
    {
        $audit = self::runAudit();

        fwrite(\STDERR, $audit['stderr']);

        $report = json_decode($audit['stdout'], true);

        if (!\is_array($report)) {
            fwrite(\STDERR, \sprintf(
                "directives:audit produced no parseable JSON (exit %d).\nstdout: %s\n",
                $audit['exit'],
                $audit['stdout'],
            ));

            return $audit['exit'] !== 0 ? $audit['exit'] : self::FAILURE;
        }

        fwrite(\STDOUT, $audit['stdout']);

        if (isset($report['error'])) {
            // The command already chose an exit code for this; ours is only to
            // propagate it, not to reinterpret it.
            return $audit['exit'];
        }

        if ($audit['exit'] !== 0 && $audit['exit'] !== 2) {
            // 3 (config error) and 4 (incomplete run) already disqualify the
            // report from judging anything; nothing this gate adds changes
            // that verdict.
            return $audit['exit'];
        }

        $enumerated = self::runEnumeration();

        $auditedSites = self::thresholdSites($report['directives'] ?? []);
        $enumeratedSites = self::thresholdSites($enumerated);

        $onlyAudited = array_diff($auditedSites, $enumeratedSites);
        $onlyEnumerated = array_diff($enumeratedSites, $auditedSites);

        if ($onlyAudited === [] && $onlyEnumerated === []) {
            fwrite(\STDOUT, \sprintf(
                "population check: %d @qmx-threshold site(s) in the audit match the enumeration exactly.\n",
                \count($auditedSites),
            ));

            return $audit['exit'];
        }

        fwrite(\STDOUT, \sprintf(
            "POPULATION MISMATCH: audit judged %d @qmx-threshold site(s), enumeration found %d.\n",
            \count($auditedSites),
            \count($enumeratedSites),
        ));
        foreach ($onlyEnumerated as $site) {
            fwrite(\STDOUT, \sprintf("  enumerated but not judged: %s\n", $site));
        }
        foreach ($onlyAudited as $site) {
            fwrite(\STDOUT, \sprintf("  judged but not enumerated: %s\n", $site));
        }

        return self::EXIT_POPULATION_MISMATCH;
    }

    /** @return array{stdout: string, stderr: string, exit: int} */
    private static function runAudit(): array
    {
        return Process::run(
            ['php', 'bin/qmx', 'directives', self::TARGET, '--format=json'],
            self::rootPath(),
        );
    }

    /**
     * One authored `@qmx-threshold` site per line, as `file\tline\tchannel\tvalues`.
     *
     * Shaped identically to the entries {@see thresholdSites()} reads out of
     * the audit's own JSON (`file`, `line`, `target`, keyed the same way): one
     * shape read by one method, not two shapes reconciled by a looser
     * parameter type.
     *
     * @return list<array{file: string, line: int, target: string}>
     */
    private static function runEnumeration(): array
    {
        $result = Process::run(['php', 'scripts/enumerate-inline-directives.php', 'src'], self::rootPath());

        if ($result['exit'] !== 0) {
            throw new RuntimeException(\sprintf(
                "enumerate-inline-directives.php failed (exit %d):\n%s",
                $result['exit'],
                $result['stderr'],
            ));
        }

        $rows = [];
        foreach (explode("\n", $result['stdout']) as $line) {
            if ($line === '') {
                continue;
            }

            $columns = explode("\t", $line);
            $rows[] = ['file' => $columns[0], 'line' => (int) $columns[1], 'target' => $columns[2]];
        }

        return $rows;
    }

    /**
     * `file:line:target` for every `form === 'threshold'` entry — the only form
     * `enumerate-inline-directives.php` extracts, so both sides of the
     * comparison are the same population by construction. `form` is optional
     * in the shape because {@see runEnumeration()}'s rows never carry it (they
     * are all threshold sites by construction) while the audit's JSON entries
     * always do.
     *
     * @param list<array{file: string, line: int, target: string, form?: string}> $directives
     *
     * @return list<string>
     */
    private static function thresholdSites(array $directives): array
    {
        $sites = [];

        foreach ($directives as $directive) {
            if (($directive['form'] ?? 'threshold') !== 'threshold') {
                continue;
            }

            $sites[] = \sprintf('%s:%d:%s', $directive['file'], $directive['line'], $directive['target']);
        }

        sort($sites);

        return $sites;
    }

    private static function rootPath(): string
    {
        $resolved = realpath(self::ROOT);

        if ($resolved === false) {
            throw new RuntimeException('Cannot resolve the repository root.');
        }

        return $resolved;
    }
}

exit(Gate::main());
