<?php

declare(strict_types=1);

namespace QmxDirectiveAuditGate;

use QmxFindingGate\Process;
use RuntimeException;

/**
 * `composer check:self`'s own wrapper around `bin/qmx directives src/`.
 *
 * `DirectivesCommand::exitCodeFor()` returns 0 on an empty or all-`Unmeasured`
 * verdict list — correctly, for the user-facing command: a tree with no
 * directives is not an error. But that same leniency means this CI step would
 * stay green through a regression in directive extraction, a widened
 * addressability refusal, or an `exclude_paths`/`exclude_namespaces` entry that
 * eats the analysed file set: every one of those shrinks or empties what the
 * audit judges without the audit's own exit code ever noticing.
 *
 * The fix is not to change the command — the empty-tree answer is correct — but
 * two checks of its own, run in this order:
 *
 * 1. **Population**, by multiset: the audit's `@qmx-threshold` sites
 *    (`file:line:target`, one count per occurrence) must match, occurrence for
 *    occurrence, the population
 *    `docs/internal/plans/rule-vocabulary/enumeration-threshold-directives.tsv`
 *    records — generated by {@see ../scripts/enumerate-inline-directives.php}
 *    through a tokenizer scan of `src/` that consults no configuration and so
 *    cannot be narrowed by one. A plain set diff would collapse two authored
 *    directives on the same site into one and never notice one of them going
 *    missing; the multiset does not.
 *
 *    **This pair is not two independent witnesses.** The enumeration script
 *    keeps a hand-copied duplicate of
 *    {@see \Qualimetrix\Analysis\Policy\Inline\Contract\ThresholdOverrideExtractor}'s
 *    private extraction pattern, and
 *    `ThresholdDirectivePatternSyncTest` forces the copy to stay byte-identical
 *    to the original — so a regex-level regression in the pattern itself (a
 *    class narrowed, an anchor loosened) is authored once and lands in both
 *    measurements, and this check cannot see it. What it does catch is every
 *    disagreement that is *not* pattern-level: the audit and the enumerator
 *    reach the pattern through unrelated pipelines — file discovery,
 *    `exclude_paths`/`exclude_namespaces`, addressability refusal, rule
 *    selection — and none of that machinery is shared, so a regression there
 *    still shows up as a mismatch.
 *
 * 2. **Non-emptiness of what was actually measured**: population matching is
 *    silent when every `@qmx-threshold` site becomes
 *    `DirectiveEffect::Unmeasured` — a widened addressability refusal or a
 *    disabled producer removes nothing from the population `array_diff` (or
 *    its multiset form) would see, it just stops any of those sites from being
 *    judged. So once the populations agree and are non-empty, this gate also
 *    demands at least one verdict with `effect !== 'unmeasured'` — mirroring
 *    the same floor {@see ./directive-narrow-control.php} already enforces on
 *    each half of its own comparison.
 */

require __DIR__ . '/finding-gate/Process.php';

final class Gate
{
    private const string ROOT = __DIR__ . '/..';

    private const string TARGET = 'src/';

    /** Distinct from the audit's own exit codes (0-4): a population mismatch is this gate's own finding. */
    private const int EXIT_POPULATION_MISMATCH = 5;

    /** All `@qmx-threshold` sites matched the enumeration, but not one produced a measured verdict. */
    private const int EXIT_NO_MEASURED_VERDICTS = 6;

    private const int FAILURE = 1;

    public static function main(): int
    {
        $audit = self::runAudit();

        fwrite(\STDERR, $audit['stderr']);

        $report = json_decode($audit['stdout'], true);

        if (!\is_array($report)) {
            fwrite(\STDERR, \sprintf(
                "directives:audit produced no parseable JSON (exit %d).\nstdout: %s\n",
                $audit['exit'],
                $audit['stdout'],
            ));

            return $audit['exit'] !== 0 ? $audit['exit'] : self::FAILURE;
        }

        fwrite(\STDOUT, $audit['stdout']);

        if (isset($report['error'])) {
            // The command already chose an exit code for this; ours is only to
            // propagate it, not to reinterpret it.
            return $audit['exit'];
        }

        if ($audit['exit'] !== 0 && $audit['exit'] !== 2) {
            // 3 (config error) and 4 (incomplete run) already disqualify the
            // report from judging anything; nothing this gate adds changes
            // that verdict.
            return $audit['exit'];
        }

        $directives = $report['directives'] ?? [];
        $enumerated = self::runEnumeration();

        $auditedSites = self::thresholdSites($directives);
        $enumeratedSites = self::thresholdSites($enumerated);

        [$onlyAudited, $onlyEnumerated] = self::multisetDiff($auditedSites, $enumeratedSites);

        if ($onlyAudited !== [] || $onlyEnumerated !== []) {
            fwrite(\STDOUT, \sprintf(
                "POPULATION MISMATCH: audit judged %d @qmx-threshold site(s), enumeration found %d.\n",
                \count($auditedSites),
                \count($enumeratedSites),
            ));
            foreach ($onlyEnumerated as $site => $missing) {
                fwrite(\STDOUT, \sprintf("  enumerated but not judged: %s (x%d)\n", $site, $missing));
            }
            foreach ($onlyAudited as $site => $surplus) {
                fwrite(\STDOUT, \sprintf("  judged but not enumerated: %s (x%d)\n", $site, $surplus));
            }

            return self::EXIT_POPULATION_MISMATCH;
        }

        if ($auditedSites === []) {
            fwrite(\STDOUT, "population check: no @qmx-threshold sites in scope; nothing to floor-check.\n");

            return $audit['exit'];
        }

        $measured = self::measuredThresholdCount($directives);

        if ($measured === 0) {
            fwrite(\STDOUT, \sprintf(
                "ALL @qmx-THRESHOLD VERDICTS UNMEASURED: %d site(s) match the enumeration exactly, but not one" .
                    " produced a measured verdict — every one is `effect === \"unmeasured\"`. Population agreement" .
                    " alone does not prove the audit judged anything.\n",
                \count($auditedSites),
            ));

            return self::EXIT_NO_MEASURED_VERDICTS;
        }

        fwrite(\STDOUT, \sprintf(
            "population check: %d @qmx-threshold site(s) in the audit match the enumeration exactly, %d measured.\n",
            \count($auditedSites),
            $measured,
        ));

        return $audit['exit'];
    }

    /** @return array{stdout: string, stderr: string, exit: int} */
    private static function runAudit(): array
    {
        return Process::run(
            ['php', 'bin/qmx', 'directives', self::TARGET, '--format=json'],
            self::rootPath(),
        );
    }

    /**
     * One authored `@qmx-threshold` site per line, as `file\tline\tchannel\tvalues`.
     *
     * Shaped identically to the entries {@see thresholdSites()} reads out of
     * the audit's own JSON (`file`, `line`, `target`, keyed the same way): one
     * shape read by one method, not two shapes reconciled by a looser
     * parameter type.
     *
     * @return list<array{file: string, line: int, target: string}>
     */
    private static function runEnumeration(): array
    {
        $result = Process::run(['php', 'scripts/enumerate-inline-directives.php', 'src'], self::rootPath());

        if ($result['exit'] !== 0) {
            throw new RuntimeException(\sprintf(
                "enumerate-inline-directives.php failed (exit %d):\n%s",
                $result['exit'],
                $result['stderr'],
            ));
        }

        $rows = [];
        foreach (explode("\n", $result['stdout']) as $line) {
            if ($line === '') {
                continue;
            }

            $columns = explode("\t", $line);
            $rows[] = ['file' => $columns[0], 'line' => (int) $columns[1], 'target' => $columns[2]];
        }

        return $rows;
    }

    /**
     * `file:line:target` for every `form === 'threshold'` entry — the only form
     * `enumerate-inline-directives.php` extracts, so both sides of the
     * comparison are the same population by construction. `form` is optional
     * in the shape because {@see runEnumeration()}'s rows never carry it (they
     * are all threshold sites by construction) while the audit's JSON entries
     * always do.
     *
     * Not deduplicated: two authored directives can share one `file:line:target`
     * (the same declaration threshold-overridden twice is a mistake this gate
     * should surface, not one {@see multisetDiff()} should hide by collapsing
     * both occurrences into one).
     *
     * @param list<array{file: string, line: int, target: string, form?: string}> $directives
     *
     * @return list<string>
     */
    private static function thresholdSites(array $directives): array
    {
        $sites = [];

        foreach ($directives as $directive) {
            if (($directive['form'] ?? 'threshold') !== 'threshold') {
                continue;
            }

            $sites[] = \sprintf('%s:%d:%s', $directive['file'], $directive['line'], $directive['target']);
        }

        sort($sites);

        return $sites;
    }

    /**
     * Occurrence-counted difference between two site lists in both directions.
     *
     * A plain `array_diff()` treats its input as a set: two authored directives
     * on the same site collapse into one before the comparison ever runs, so a
     * missing occurrence with a surviving twin at the same site is invisible.
     * Counting occurrences per site keeps that case visible.
     *
     * @param list<string> $left
     * @param list<string> $right
     *
     * @return array{0: array<string, int>, 1: array<string, int>} surplus-in-$left, surplus-in-$right, both keyed by site
     */
    private static function multisetDiff(array $left, array $right): array
    {
        $leftCounts = self::occurrenceCounts($left);
        $rightCounts = self::occurrenceCounts($right);

        $onlyLeft = [];
        $onlyRight = [];

        foreach (array_unique([...array_keys($leftCounts), ...array_keys($rightCounts)]) as $site) {
            $delta = ($leftCounts[$site] ?? 0) - ($rightCounts[$site] ?? 0);

            if ($delta > 0) {
                $onlyLeft[$site] = $delta;
            } elseif ($delta < 0) {
                $onlyRight[$site] = -$delta;
            }
        }

        return [$onlyLeft, $onlyRight];
    }

    /**
     * @param list<string> $sites
     *
     * @return array<string, int>
     */
    private static function occurrenceCounts(array $sites): array
    {
        $counts = [];

        foreach ($sites as $site) {
            $counts[$site] = ($counts[$site] ?? 0) + 1;
        }

        return $counts;
    }

    /**
     * How many authored `@qmx-threshold` sites produced an actual verdict.
     *
     * Population agreement alone does not prove that: a directive stays in the
     * population — and in the enumeration — even after
     * {@see \Qualimetrix\Analysis\Policy\Inline\Directive\ThresholdDirectiveAudit::unmeasurableReason()}
     * gives up on judging it, because it is reported back as
     * `DirectiveEffect::Unmeasured` rather than dropped. A regression that
     * widens that refusal (or disables every addressed producer) leaves the
     * multiset comparison above satisfied while judging nothing; this is the
     * check that would still catch it.
     *
     * @param list<array{form?: string, effect?: string}> $directives
     */
    private static function measuredThresholdCount(array $directives): int
    {
        $count = 0;

        foreach ($directives as $directive) {
            if (($directive['form'] ?? null) === 'threshold' && ($directive['effect'] ?? null) !== 'unmeasured') {
                ++$count;
            }
        }

        return $count;
    }

    private static function rootPath(): string
    {
        $resolved = realpath(self::ROOT);

        if ($resolved === false) {
            throw new RuntimeException('Cannot resolve the repository root.');
        }

        return $resolved;
    }
}

exit(Gate::main());
