#!/usr/bin/env python3
"""Freeze the carrier ranges the promise ledger cites, and prove the freeze covers all of them.

The ledger (promise-effect/promise-ledger.tsv) states what the
product promises, read from external carriers: website pages and contract docblocks. Its companion
promise-ledger-frozen-ranges.tsv pins the exact line ranges those citations point at, so that a
later edit to a carrier cannot change a promise silently.

The companion file used to be produced by a throwaway script that was not kept, and the run that
produced it missed one cited range. A missing range is the worst failure this file can have: the
one carrier nobody watched is exactly the one that was rewritten. So this script asserts coverage
in both directions — every cited range is frozen, and every frozen range is still cited — in
addition to comparing the hashes.

    python3 scripts/promise-ledger-freeze.py            # rewrite the frozen file from the tree
    python3 scripts/promise-ledger-freeze.py --check    # assert it matches the tree; 0 ok, 1 drift

Exit codes: 0 agreed, 1 a range drifted or coverage is incomplete, 2 the input cannot be read.
"""

from __future__ import annotations

import hashlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MEASUREMENT = ROOT / "promise-effect"
LEDGER = MEASUREMENT / "promise-ledger.tsv"
FROZEN = MEASUREMENT / "promise-ledger-frozen-ranges.tsv"
P1_SET = MEASUREMENT / "p1-file-set.tsv"

# The computed overlap line, marked so `--check` can find the value it compares.
OVERLAP_MARK = "#   P1 ∩ frozen:"

# A citation is `<path>:<line>` or `<path>:<line>-<line>`. Only paths inside the two trees the
# ledger declares as carriers are citations; anything else in a note is prose.
CITATION = re.compile(r"((?:website/docs|src)/[A-Za-z0-9_./-]+\.(?:md|php)):(\d+)(?:-(\d+))?")

COLUMNS = "file\tfirst_line\tlast_line\tsha256_16\towner_package\tfirst_line_text"

HEADER = """\
# FROZEN PROMISE-CARRIER RANGES — companion to promise-ledger.tsv.
# Tree {tree}. Date: {date}.
#
# Each ledger citation is frozen at line-range granularity with a hash of its
# exact text. File granularity would prevent legitimate changes elsewhere in a
# carrier while still failing to identify the precise promise being protected.
#
# GENERATED BY scripts/promise-ledger-freeze.py. The script collects every
# `path:line[-line]` citation from promise-ledger.tsv, reads exactly those lines,
# and hashes their newline-joined text without a trailing newline. Paths under
# src/** belong to the product-source set; paths under website/** belong to the
# website-documentation set.
#
# `--check` verifies coverage in both directions: every cited range is frozen,
# every frozen range is still cited, and every stored hash matches. Hashes guard
# exact text, not meaning; moving a range by inserting lines above it therefore
# causes conservative drift.
#
# The following overlap with p1-file-set.tsv is recomputed on every run:
{overlap}
# The ranges overlapping that set are contract docblocks outside signatures and
# bodies. Other ranges live under website/docs/**, and options classes are not
# carriers because the ledger does not cite them.
#
# A carrier change is expected when its contract or documentation changes. In
# that case, re-derive the affected ledger rows and regenerate this file; an
# unreviewed silent carrier change is the failure this guard detects.
"""


class InputError(Exception):
    """The measurement cannot be read at all — exit 2, never a silent partial answer."""


def p1_files() -> set[str]:
    """The product-source promise files, read from their artefact rather than retyped."""
    if not P1_SET.exists():
        raise InputError(f"cannot read {P1_SET}")
    files = set()
    for line in P1_SET.read_text(encoding="utf-8").split("\n"):
        if not line or line.startswith("#") or line.startswith("file\t"):
            continue
        files.add(line.split("\t")[0])
    return files


def overlap_line(rows) -> str:
    """Which frozen ranges fall inside the product-source set — computed, not asserted.

    The paragraph this feeds used to carry a hand-written "EXACTLY THREE" beside `git rev-parse
    HEAD`, so every later rewrite re-dated a claim a human had checked once. Here the claim is
    recomputed at every write and compared at every `--check`.
    """
    inside = [f"{f}:{a}-{b}" for f, a, b, _, _, _ in rows if f in p1_files()]
    return OVERLAP_MARK + " " + (", ".join(inside) if inside else "(none)")


def sha16(lines: list[str]) -> str:
    return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest()[:16]


def owner(path: str) -> str:
    return "P1 (product source)" if path.startswith("src/") else "P6 (website documentation)"


def collect() -> list[tuple[str, int, int, str, str, str]]:
    """Every range cited anywhere in the ledger body, hashed against the working tree."""
    text = LEDGER.read_text(encoding="utf-8")
    cited: set[tuple[str, int, int]] = set()
    for path, first, last in CITATION.findall(text):
        cited.add((path, int(first), int(last or first)))

    rows = []
    cache: dict[str, list[str]] = {}
    for path, first, last in sorted(cited):
        target = ROOT / path
        if not target.exists():
            raise InputError(f"cited carrier does not exist: {path}")
        if path not in cache:
            cache[path] = target.read_text(encoding="utf-8").split("\n")
        body = cache[path]
        if last > len(body):
            raise InputError(f"cited range runs past the end of {path}: {first}-{last}")
        window = body[first - 1 : last]
        # first_line_text is a human signpost only; stripped and clipped to 70 characters,
        # the convention the first snapshot used. The sha is what actually binds.
        rows.append((path, first, last, sha16(window), owner(path), window[0].strip()[:70]))
    return rows


def render(rows) -> str:
    tree = subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "HEAD"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    date = subprocess.run(
        ["git", "-C", str(ROOT), "log", "-1", "--format=%cs"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    head = HEADER.format(tree=tree, date=date, overlap=overlap_line(rows))
    body = "\n".join(
        "\t".join([f, str(a), str(b), s, o, t]) for f, a, b, s, o, t in rows
    )
    return head + COLUMNS + "\n" + body + "\n"


def parse_frozen() -> dict[tuple[str, int, int], str]:
    out = {}
    for line in FROZEN.read_text(encoding="utf-8").split("\n"):
        if not line or line.startswith("#") or line.startswith("file\t"):
            continue
        f = line.split("\t")
        out[(f[0], int(f[1]), int(f[2]))] = f[3]
    return out


def stored_overlap() -> str | None:
    for line in FROZEN.read_text(encoding="utf-8").split("\n"):
        if line.startswith(OVERLAP_MARK):
            return line
        if not line.startswith("#"):
            return None
    return None


def main() -> int:
    if not LEDGER.exists():
        print(f"cannot read {LEDGER}", file=sys.stderr)
        return 2
    try:
        rows = collect()
    except InputError as error:
        print(error, file=sys.stderr)
        return 2
    if "--check" not in sys.argv:
        try:
            rendered = render(rows)
        except InputError as error:
            print(error, file=sys.stderr)
            return 2
        FROZEN.write_text(rendered, encoding="utf-8")
        print(f"wrote {FROZEN.relative_to(ROOT)}: {len(rows)} ranges")
        return 0

    frozen = parse_frozen()
    try:
        computed = overlap_line(rows)
    except InputError as error:
        print(error, file=sys.stderr)
        return 2
    stored = stored_overlap()
    cited = {(f, a, b): s for f, a, b, s, _, _ in rows}
    missing = sorted(set(cited) - set(frozen))
    stale = sorted(set(frozen) - set(cited))
    drifted = sorted(k for k in set(cited) & set(frozen) if cited[k] != frozen[k])

    for k in missing:
        print(f"NOT FROZEN (cited by the ledger, absent here): {k[0]}:{k[1]}-{k[2]}")
    for k in stale:
        print(f"STALE (frozen here, no longer cited): {k[0]}:{k[1]}-{k[2]}")
    for k in drifted:
        print(f"DRIFTED (text changed): {k[0]}:{k[1]}-{k[2]} {frozen[k]} -> {cited[k]}")

    if stored is not None and stored.strip() != computed.strip():
        # The ownership overlap is re-derived rather than re-dated.
        print(f"DoD-2 OVERLAP CHANGED:\n  frozen file says {stored.strip()}\n  the tree says   {computed.strip()}")

    if missing or stale or drifted:
        print(f"\n{len(cited)} cited, {len(frozen)} frozen: the freeze does not cover the ledger.")
        return 1
    if stored is not None and stored.strip() != computed.strip():
        return 1
    print(f"{len(cited)} cited ranges, all frozen and unchanged.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
